#!/usr/bin/env python3
"""
extract_workbook_cuts - data cuts feeding the consolidated data workbook.

Pivots the classified full-history corpus (_corpus.iter_records: deduped,
registry-first classification, vclass/bgroup per record) into wide FY-columned
CSVs under projects/distributed_shipbuilding/sam/award_analysis/extracted/ — the
Award Analysis workbook's own data dir, regenerated by this script so the
copies never drift from the research basis.

Programs are virginia / columbia / ddg: the submarine corpus is split into
two top-level programs by each record's vessel class (deterministic — every
submarine PIID carries exactly one class in its scope metadata, so vclass is
per-PIID). Lane sharing ("another same-program PIID") is therefore
within-class for the submarine programs.

Descriptive only: dollars / record counts / dates by dimension. No gates, no
signal scoring. FY = subAwardDate federal FY; columns run ≤FY12 (rollup of the
sparse early-DDG dribble) then FY2013..FY2026. Dollar cells are supplier-role
records except wb_annual_program.csv, which carries every role so supplier
share is visible. Work type is the RECORD's bucket (not the vendor's modal
lane) — this is a data cut, not the vendor-level signal rollup.

CSVs:
  wb_annual_program.csv   (program, role) x FY $M + n_records (all roles)
  wb_role_piid.csv        (program, role, piid) x FY $M + n_records (all
                          roles - the workbook's Role Detail leaf data; the
                          By Role grid and By PIID's all-roles counts derive
                          live from it)
  wb_annual_worktype.csv  (program, work_type) x FY $M and x FY n_records
  wb_annual_class.csv     (program, cut, work_type + 'all') x FY $M; cut =
                          Virginia (virginia) / Columbia (columbia) /
                          GD-BIW/HII-Ingalls (ddg)
  wb_annual_piid.csv      (program, piid) x FY $M + scope meta + data_status +
                          all-roles and supplier-only record counts
  wb_vendor_fy.csv        (program, vendor_key) x FY $M + name/lane/cut
                          profile/first/last/n (supplier universe); cut
                          profile is within-program for ddg (GD-BIW /
                          HII-Ingalls / both) and the vendor's CROSS-CLASS
                          footprint for virginia/columbia (Virginia-only /
                          Columbia-only / both) so class overlap stays
                          visible after the program split
  wb_piid_worktype.csv    (program, piid, work_type) lane x FY record counts
                          AND x FY $M (d_ columns - the workbook's Lane
                          Detail leaf data) + lane $M total, first/last
                          award, unique vendors,
                          repeat-award share (records to vendors with >1 record
                          in the lane), shared-vendor pct (lane vendors also
                          on the same work type on another same-program PIID)
                          and its family-wide variant (same test across all
                          PIIDs of the family - both submarine classes for
                          virginia/columbia lanes; equal to the program pct
                          for ddg); the vendor/repeat/shared columns are
                          script-side reconciliation - the workbook derives
                          them live from wb_vendor_lane
  wb_vendor_lane.csv      (program, family, piid, work_type, vendor) record
                          count + $M - the lane-level vendor detail behind the
                          live Vendors / Repeat % / Shared % formulas; family
                          (Submarines / DDG-51) keys the fleet-wide footprint
                          column; vendor_name is the corpus-wide modal name
                          (one display name per UEI key everywhere)

Console prints per-cut full-history and FY22-25 totals; all cuts of one
program must agree to the cent (asserted).
"""
from __future__ import annotations

import csv
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _corpus import REPO, iter_records, load_registry, scope_meta

OUT = REPO / "projects/distributed_shipbuilding/sam/award_analysis/extracted"
FY_MIN, FY_MAX = 2013, 2026
FY_COLS = ["le_fy12"] + [f"fy{y}" for y in range(FY_MIN, FY_MAX + 1)]
CUTS = {"virginia": ("vclass", ["Virginia"]),
        "columbia": ("vclass", ["Columbia"]),
        "ddg": ("bgroup", ["GD-BIW", "HII-Ingalls"])}
PROG_ORDER = {p: n for n, p in enumerate(CUTS)}   # output/display order
SOURCES = ("submarines", "ddg")                   # corpus dirs to read
FAMILY = {"virginia": "Submarines", "columbia": "Submarines",
          "ddg": "DDG-51"}


def fy_col(fy: int) -> str:
    return "le_fy12" if fy <= 2012 else f"fy{fy}"


def data_status(n: int) -> str:
    return ("none" if n == 0 else "very-thin" if n < 50 else "thin" if n < 300
            else "usable" if n < 1500 else "robust")


def new_series():
    return {c: 0.0 for c in FY_COLS}


def main() -> int:
    registry = load_registry()
    prog_role = defaultdict(lambda: {"$": new_series(), "n": 0})
    role_piid = defaultdict(lambda: {"$": new_series(), "n": 0})
    worktype = defaultdict(lambda: {"$": new_series(),
                                    "n": {c: 0 for c in FY_COLS}})
    cls = defaultdict(lambda: new_series())
    piid = {}
    vendor = {}
    pw = {}
    # display name per vendor key, dollar-weighted across the FULL corpus so
    # a UEI renders identically on every program's rows
    names_all = defaultdict(lambda: defaultdict(float))
    # capability tag per vendor key: dollar-weighted modal (naics4, naics_desc)
    # from the SAM enrichment - a finer-than-bucket descriptor used on the
    # jump-ball leaf so a reviewer can see whether a multi-vendor work-type lane
    # holds vendors that actually overlap on the same component.
    naics_all = defaultdict(lambda: defaultdict(float))

    for source in SOURCES:
        for p, m in scope_meta(source).items():
            program = ((m.get("class") or "").strip().lower()
                       if source == "submarines" else "ddg")
            assert program in CUTS, f"{p}: unmapped class {m.get('class')!r}"
            piid[(program, p)] = {"meta": m, "$": new_series(),
                                  "n_all": 0, "n_sup": 0}
        for rec in iter_records(source, registry=registry):
            assert rec["fy"] is not None, f"undated record {rec['report_id']!r}"
            program = (rec["vclass"].strip().lower()
                       if source == "submarines" else "ddg")
            cut_field, _ = CUTS[program]
            col = fy_col(rec["fy"])
            d = rec["dollar_m"]

            prog_role[(program, rec["role"])]["$"][col] += d
            prog_role[(program, rec["role"])]["n"] += 1
            role_piid[(program, rec["role"], rec["piid"])]["$"][col] += d
            role_piid[(program, rec["role"], rec["piid"])]["n"] += 1
            piid[(program, rec["piid"])]["n_all"] += 1

            if rec["role"] != "supplier":
                continue
            worktype[(program, rec["bucket"])]["$"][col] += d
            worktype[(program, rec["bucket"])]["n"][col] += 1
            cls[(program, rec[cut_field], rec["bucket"])][col] += d
            cls[(program, rec[cut_field], "all")][col] += d
            piid[(program, rec["piid"])]["$"][col] += d
            piid[(program, rec["piid"])]["n_sup"] += 1

            key = (program, rec["vendor_key"])
            g = vendor.get(key)
            if g is None:
                g = vendor[key] = {"$": new_series(),
                                   "bucket_all": defaultdict(float),
                                   "cut_n": defaultdict(int),
                                   "first": "", "last": "", "n": 0}
            g["$"][col] += d
            names_all[rec["vendor_key"]][
                (rec["parent_name"] or rec["vendor"]).upper()] += d
            g["bucket_all"][rec["bucket"]] += d
            g["cut_n"][rec[cut_field]] += 1
            g["n"] += 1
            date = rec["date"][:10]
            if date:
                if not g["first"] or date < g["first"]:
                    g["first"] = date
                if date > g["last"]:
                    g["last"] = date

            lane = pw.get((program, rec["piid"], rec["bucket"]))
            if lane is None:
                lane = pw[(program, rec["piid"], rec["bucket"])] = {
                    "n": {c: 0 for c in FY_COLS}, "$": 0.0,
                    "$fy": new_series(),
                    "vend": defaultdict(int), "vend_d": defaultdict(float),
                    "vfy_d": defaultdict(new_series),
                    "vfy_n": defaultdict(lambda: {c: 0 for c in FY_COLS}),
                    "vfirst": {}, "vlast": {},
                    "first": "", "last": ""}
            lane["n"][col] += 1
            lane["$"] += d
            lane["$fy"][col] += d
            vk = rec["vendor_key"]
            lane["vend"][vk] += 1
            lane["vend_d"][vk] += d
            lane["vfy_d"][vk][col] += d
            lane["vfy_n"][vk][col] += 1
            naics_all[vk][(rec["naics4"] or "", rec["naics_desc"] or "")] += d
            if date:
                if not lane["first"] or date < lane["first"]:
                    lane["first"] = date
                if date > lane["last"]:
                    lane["last"] = date
                if not lane["vfirst"].get(vk) or date < lane["vfirst"][vk]:
                    lane["vfirst"][vk] = date
                if date > lane["vlast"].get(vk, ""):
                    lane["vlast"][vk] = date

    OUT.mkdir(parents=True, exist_ok=True)

    def series_out(s, nd=3):
        vals = [round(s[c], nd) for c in FY_COLS]
        return vals + [round(sum(s.values()), nd)]

    def disp_name(vk: str) -> str:
        return max(names_all[vk].items(), key=lambda kv: kv[1])[0]

    def capability(vk: str) -> tuple[str, str]:
        """(naics4, naics_desc) - the vendor's dollar-weighted modal SAM
        enrichment NAICS. ('', '') when the vendor was never enriched."""
        items = [kv for kv in naics_all[vk].items() if kv[0] != ("", "")]
        if not items:
            return ("", "")
        return max(items, key=lambda kv: kv[1])[0]

    # ---- wb_annual_program -----------------------------------------------------
    with (OUT / "wb_annual_program.csv").open("w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["program", "role"] + FY_COLS + ["total", "n_records"])
        for (program, role), v in sorted(prog_role.items(),
                                         key=lambda kv: (PROG_ORDER[kv[0][0]],
                                                         -sum(kv[1]["$"].values()))):
            w.writerow([program, role] + series_out(v["$"]) + [v["n"]])

    # ---- wb_role_piid ------------------------------------------------------------
    with (OUT / "wb_role_piid.csv").open("w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["program", "role", "piid"] + FY_COLS
                   + ["total", "n_records"])
        for (program, role, p), v in sorted(
                role_piid.items(),
                key=lambda kv: (PROG_ORDER[kv[0][0]], kv[0][1],
                                -sum(kv[1]["$"].values()))):
            w.writerow([program, role, p] + series_out(v["$"]) + [v["n"]])

    # ---- wb_annual_worktype ------------------------------------------------------
    with (OUT / "wb_annual_worktype.csv").open("w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["program", "work_type"] + FY_COLS + ["total"]
                   + [f"n_{c}" for c in FY_COLS] + ["n_total"])
        for (program, bucket), v in sorted(
                worktype.items(), key=lambda kv: (PROG_ORDER[kv[0][0]],
                                                  -sum(kv[1]["$"].values()))):
            ns = [v["n"][c] for c in FY_COLS]
            w.writerow([program, bucket] + series_out(v["$"]) + ns + [sum(ns)])

    # ---- wb_annual_class ---------------------------------------------------------
    with (OUT / "wb_annual_class.csv").open("w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["program", "cut", "work_type"] + FY_COLS + ["total"])
        def _cls_sort(kv):
            (program, cut, bucket) = kv[0]
            return (PROG_ORDER[program], CUTS[program][1].index(cut),
                    bucket != "all", -sum(kv[1].values()))
        for (program, cut, bucket), s in sorted(cls.items(), key=_cls_sort):
            w.writerow([program, cut, bucket] + series_out(s))

    # ---- wb_annual_piid ----------------------------------------------------------
    with (OUT / "wb_annual_piid.csv").open("w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["program", "piid", "vessel_class", "builder", "label",
                    "data_status", "n_records_full_history",
                    "n_records_supplier"] + FY_COLS + ["total"])
        for (program, p), v in sorted(piid.items(),
                                      key=lambda kv: (PROG_ORDER[kv[0][0]],
                                                      -kv[1]["n_all"])):
            m = v["meta"]
            label = " ".join((m.get("label") or "").split())
            w.writerow([program, p, (m.get("class") or "").strip(),
                        (m.get("group") or m.get("prime") or "").strip(), label,
                        data_status(v["n_all"]), v["n_all"], v["n_sup"]]
                       + series_out(v["$"]))

    # ---- wb_vendor_fy --------------------------------------------------------------
    with (OUT / "wb_vendor_fy.csv").open("w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["program", "vendor_uei", "vendor_name", "work_type",
                    "cut_profile", "first_award", "last_award", "n_records"]
                   + FY_COLS + ["total"])
        for (program, key), g in sorted(
                vendor.items(), key=lambda kv: (PROG_ORDER[kv[0][0]],
                                                -sum(kv[1]["$"].values()))):
            if program == "ddg":
                a, b = CUTS[program][1]
                on_a, on_b = g["cut_n"][a] > 0, g["cut_n"][b] > 0
                profile = ("both" if on_a and on_b else f"{a}-only" if on_a
                           else f"{b}-only")
            else:
                # cross-class footprint: the within-program cut is degenerate
                other = "columbia" if program == "virginia" else "virginia"
                profile = ("both" if (other, key) in vendor
                           else f"{CUTS[program][1][0]}-only")
            w.writerow([program, key, disp_name(key),
                        max(g["bucket_all"].items(), key=lambda kv: kv[1])[0],
                        profile, g["first"], g["last"], g["n"]]
                       + series_out(g["$"]))

    # ---- wb_piid_worktype ----------------------------------------------------------
    vend_piids = defaultdict(set)
    vend_piids_fam = defaultdict(set)
    piid_lane_n = defaultdict(int)
    for (program, p, b), lane in pw.items():
        for vk in lane["vend"]:
            vend_piids[(program, b, vk)].add(p)
            vend_piids_fam[(FAMILY[program], b, vk)].add(p)
        piid_lane_n[(program, p)] += sum(lane["n"].values())

    def _pw_sort(kv):
        (program, p, b) = kv[0]
        return (PROG_ORDER[program], -piid_lane_n[(program, p)], p,
                -sum(kv[1]["n"].values()), b)

    with (OUT / "wb_piid_worktype.csv").open("w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["program", "piid", "vessel_class", "builder", "work_type",
                    "first_award", "last_award", "n_vendors",
                    "repeat_award_share", "shared_vendor_pct",
                    "shared_vendor_pct_family", "dollars_total"]
                   + [f"d_{c}" for c in FY_COLS]
                   + [f"n_{c}" for c in FY_COLS] + ["n_total"])
        for (program, p, b), lane in sorted(pw.items(), key=_pw_sort):
            ns = [lane["n"][c] for c in FY_COLS]
            n = sum(ns)
            vend = lane["vend"]
            repeat = sum(cnt for cnt in vend.values() if cnt > 1) / n
            shared = sum(1 for vk in vend
                         if len(vend_piids[(program, b, vk)]) > 1) / len(vend)
            shared_fam = sum(
                1 for vk in vend
                if len(vend_piids_fam[(FAMILY[program], b, vk)]) > 1) / len(vend)
            m = piid[(program, p)]["meta"]
            w.writerow([program, p, (m.get("class") or "").strip(),
                        (m.get("group") or m.get("prime") or "").strip(), b,
                        lane["first"], lane["last"], len(vend),
                        round(repeat, 4), round(shared, 4),
                        round(shared_fam, 4),
                        round(lane["$"], 3)]
                       + [round(lane["$fy"][c], 3) for c in FY_COLS]
                       + ns + [n])

    # ---- wb_vendor_lane ------------------------------------------------------------
    n_vl = 0
    with (OUT / "wb_vendor_lane.csv").open("w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["program", "family", "piid", "work_type", "vendor_uei",
                    "vendor_name", "n_records", "dollars"])
        for (program, p, b), lane in sorted(pw.items(), key=_pw_sort):
            for vk, cnt in sorted(lane["vend"].items(),
                                  key=lambda kv: (-kv[1], kv[0])):
                w.writerow([program, FAMILY[program], p, b, vk, disp_name(vk),
                            cnt, round(lane["vend_d"][vk], 3)])
                n_vl += 1

    # ---- wb_vendor_lane_fy ---------------------------------------------------------
    # The jump-ball LEAF: one row per (program, PIID, work type, vendor) carrying
    # the supplier's $M and record count BY subaward FY, the vendor's first/last
    # award in the lane, and a capability tag. The Re-buy Timing and Source
    # Concentration tabs derive every count/share live (COUNTIFS/MAXIFS/SUMIFS)
    # from this table; only the FY cells and dates are blue inputs. Reconciles to
    # wb_vendor_lane per vendor-lane (asserted below).
    n_vlf = 0
    with (OUT / "wb_vendor_lane_fy.csv").open("w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["program", "family", "piid", "work_type", "vendor_uei",
                    "vendor_name", "naics4", "capability",
                    "first_award", "last_award", "n_records", "dollars"]
                   + [f"d_{c}" for c in FY_COLS] + [f"n_{c}" for c in FY_COLS])
        for (program, p, b), lane in sorted(pw.items(), key=_pw_sort):
            for vk, cnt in sorted(lane["vend"].items(),
                                  key=lambda kv: (-kv[1], kv[0])):
                dfy = lane["vfy_d"][vk]
                nfy = lane["vfy_n"][vk]
                d_sum = sum(dfy.values())
                n_sum = sum(nfy.values())
                # reconcile this vendor-lane to wb_vendor_lane's totals
                assert n_sum == cnt, \
                    f"{program}/{p}/{b}/{vk}: vfy n {n_sum} != vend {cnt}"
                assert round(d_sum, 2) == round(lane["vend_d"][vk], 2), \
                    f"{program}/{p}/{b}/{vk}: vfy $ {d_sum} != {lane['vend_d'][vk]}"
                n4, ndesc = capability(vk)
                w.writerow([program, FAMILY[program], p, b, vk, disp_name(vk),
                            n4, ndesc, lane["vfirst"].get(vk, ""),
                            lane["vlast"].get(vk, ""), cnt, round(d_sum, 3)]
                           + [round(dfy[c], 3) for c in FY_COLS]
                           + [nfy[c] for c in FY_COLS])
                n_vlf += 1
    assert n_vlf == n_vl, f"vendor_lane_fy rows {n_vlf} != vendor_lane rows {n_vl}"

    # ---- console reconciliation ---------------------------------------------------
    w2225 = [f"fy{y}" for y in range(2022, 2026)]
    for program in CUTS:
        cuts = {
            "worktype": sum(sum(v["$"].values()) for (p, _), v in worktype.items()
                            if p == program),
            "class": sum(sum(s.values()) for (p, c, b), s in cls.items()
                         if p == program and b == "all"),
            "piid": sum(sum(v["$"].values()) for (p, _), v in piid.items()
                        if p == program),
            "vendor": sum(sum(g["$"].values()) for (p, _), g in vendor.items()
                          if p == program),
            "program-role": sum(prog_role[(program, "supplier")]["$"].values()),
        }
        vals = set(round(x, 2) for x in cuts.values())
        assert len(vals) == 1, f"{program} cut totals disagree: {cuts}"
        for (p, b), v in worktype.items():
            if p != program:
                continue
            for c in FY_COLS:
                lane_n = sum(l["n"][c] for (pp, _, bb), l in pw.items()
                             if pp == program and bb == b)
                assert lane_n == v["n"][c], \
                    f"{program}/{b}/{c}: lane counts {lane_n} != {v['n'][c]}"
                lane_dfy = sum(l["$fy"][c] for (pp, _, bb), l in pw.items()
                               if pp == program and bb == b)
                assert round(lane_dfy, 2) == round(v["$"][c], 2), \
                    f"{program}/{b}/{c}: lane $ {lane_dfy} != {v['$'][c]}"
        lane_d = sum(l["$"] for (pp, _, _), l in pw.items() if pp == program)
        assert round(lane_d, 2) == round(cuts["worktype"], 2), \
            f"{program}: lane $ {lane_d} != worktype $ {cuts['worktype']}"
        for (p, role), v in prog_role.items():
            if p != program:
                continue
            rp_d = sum(sum(g["$"].values()) for (pp, rr, _), g
                       in role_piid.items() if pp == program and rr == role)
            rp_n = sum(g["n"] for (pp, rr, _), g in role_piid.items()
                       if pp == program and rr == role)
            assert round(rp_d, 2) == round(sum(v["$"].values()), 2), \
                f"{program}/{role}: role-piid $ {rp_d} != {sum(v['$'].values())}"
            assert rp_n == v["n"], \
                f"{program}/{role}: role-piid n {rp_n} != {v['n']}"
        for (p, pd), v in piid.items():
            if p != program:
                continue
            lane_n = sum(sum(l["n"].values()) for (pp, ppd, _), l in pw.items()
                         if pp == program and ppd == pd)
            assert lane_n == v["n_sup"], \
                f"{program}/{pd}: lane counts {lane_n} != n_sup {v['n_sup']}"
        sup2225 = sum(worktype[(program, b)]["$"][c]
                      for (p, b) in worktype if p == program for c in w2225)
        print(f"[{program}] supplier full-history ${cuts['worktype']:,.1f}M "
              f"across all 5 cuts (agree); FY22-25 ${sup2225:,.1f}M")
    print(f"Wrote 9 CSVs to {OUT} ({n_vl} vendor-lane rows, "
          f"{n_vlf} vendor-lane-FY rows)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
