"""Distributed Shipbuilding Outsourcing Ceiling pipeline bindings.

The OOXML engine lives in the shared ``workbook_core`` package at the workspace
root. This module is intentionally thin: it binds the things specific to this
pipeline (the output path, the extracted-data dir, the docProps identity),
exposes a load_extracted_csv wrapper bound to this pipeline's data dir, and
packages the SHEETS module list via the shared packager.

The extracted/ dir holds wb_cost_base.csv and wb_anchors.csv, regenerated by
``build_ceiling_base.py`` at the pipeline root (it unions the submarine + ddg
cost funnels and stamps the verified anchor citations). Re-run it after a
cost-funnel refresh, then rebuild.
"""
from __future__ import annotations

from pathlib import Path

from workbook_core.lib import (
    package_workbook,
    load_extracted_csv as _core_load_extracted_csv,
)
import workbook_core.groups as _groups

# ---------------------------------------------------------------------------
# Tab palette - per-build override (THIS workbook only)
# ---------------------------------------------------------------------------
# Mirror the award-analysis workbook's muted black / olive / navy / slate scheme,
# mapped by group type. group_color() reads workbook_core's _COLOR dict at render
# time, so mutating it here - before build() packages the sheets - repaints the
# tabs with no sheet-module change. This mutates the shared dict IN THIS PROCESS
# ONLY; every other pipeline builds in its own process and keeps its own colors.
_TAB_PALETTE = {
    "summary":    "262626",   # black / charcoal - the answer page (Executive Summary)
    "inputs":     "556B2F",   # olive green      - the editable levers (Assumptions)
    "model":      "48596B",   # slate            - the analysis engine
    "data":       "203864",   # navy blue        - the evidence appendix
    "validation": "8694A1",   # slate, light     - Sensitivity / Tie-Outs
    "sources":    "3C4A57",   # slate, dark      - Sources
}
_groups._COLOR.update(_TAB_PALETTE)

# ---------------------------------------------------------------------------
# Pipeline bindings
# ---------------------------------------------------------------------------

WORKBOOK_DIR = Path(__file__).resolve().parents[1]   # projects/distributed_shipbuilding/workbook_outsourcing_ceiling/
PROJECT_DIR = Path(__file__).resolve().parents[2]    # projects/distributed_shipbuilding/   (build output lands here)
REPO_ROOT = Path(__file__).resolve().parents[4]      # ooxml_build_pipelines_light/
OUT = PROJECT_DIR / "20260615_Distributed Shipbuilding Outsourcing Ceiling_vS.xlsx"
EXTRACTED = WORKBOOK_DIR / "extracted"

_TITLE = "Distributed Shipbuilding Outsourcing Ceiling - Structural Ceiling + Hours-to-Dollars Bridge"
_CREATOR = "Distributed Shipbuilding analysis"
_APP = "Distributed Shipbuilding analysis"


def load_extracted_csv(name: str) -> tuple[list[str], list[list]]:
    """Load extracted/<name>.csv from this pipeline's data dir."""
    return _core_load_extracted_csv(name, EXTRACTED)


def build() -> int:
    """Render every registered sheet and package into the output xlsx."""
    from workbook_outsourcing_ceiling.sheets import SHEETS
    return package_workbook(OUT, SHEETS, title=_TITLE, creator=_CREATOR,
                            app_name=_APP, normalize_dashes=True)
